[package]
name = "codeforces"
version = "0.1.0"
authors = ["Arthur Zopellaro <arthurazsoares@gmail.com>"]
edition = "2018"

[[bin]]
name = "watermelon"
path = "src/4a.rs"

[[bin]]
name = "way-too-long-words"
path = "src/71a.rs"

[[bin]]
name = "team"
path = "src/231a.rs"
